export const LOAD_COURSE_SUCCESS='LOAD_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS='LOAD_AUTHORS_SUCCESS';
export const UPDATE_COURSE_SUCCESS='UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS='CREATE_COURSE_SUCCESS';